/**
 * FR2 and FR3 - task operations and state transitions.
 *
 * Every method runs inside a unit of work, so a task and the reminder that
 * belongs to it always change together. No method here knows what a transaction
 * is; it asks the port to run its work atomically and the data access layer
 * decides how.
 *
 * Ownership is never checked in this file. It cannot be forgotten either,
 * because the repository has no unscoped lookup: a task belonging to another
 * user simply is not found, and the caller receives {@link TaskNotFoundError}.
 */
import { TaskNotFoundError } from '../domain/errors.js';
import type { RecurrenceRule, Task, TaskChanges, TaskPriority } from '../domain/types.js';
import type { Clock } from '../ports/services.js';
import type { UnitOfWork } from '../ports/repositories.js';
import { nextOccurrence } from '../recurrence.js';
import { synchroniseReminder } from '../reminders/policy.js';
import {
  DEFAULT_REMINDER_OFFSET_MINUTES,
  normaliseTaskAttributes,
  validateTaskAttributes,
  type TaskAttributes,
} from './validation.js';

export interface CreateTaskInput {
  readonly userId: string;
  readonly title: string;
  readonly description: string | null;
  /** The task's deadline, in UTC. Converted from the user's zone upstream. */
  readonly dueAt: Date | null;
  readonly priority: TaskPriority;
  readonly recurrence: RecurrenceRule | null;
  readonly reminderOffsetMinutes?: number | undefined;
}

/** A partial update: absent leaves a field alone, null clears it. */
export interface UpdateTaskInput {
  readonly title?: string | undefined;
  readonly description?: string | null | undefined;
  readonly dueAt?: Date | null | undefined;
  readonly priority?: TaskPriority | undefined;
  readonly recurrence?: RecurrenceRule | null | undefined;
  readonly reminderOffsetMinutes?: number | undefined;
}

export interface CompleteTaskResult {
  /** The task that was completed. */
  readonly task: Task;
  /** The occurrence generated by its recurrence rule, if it had one. */
  readonly nextOccurrence: Task | null;
}

export interface TaskServiceDependencies {
  readonly unitOfWork: UnitOfWork;
  readonly clock: Clock;
}

export interface TaskService {
  list(userId: string): Promise<Task[]>;
  get(userId: string, taskId: string): Promise<Task>;
  create(input: CreateTaskInput): Promise<Task>;
  update(userId: string, taskId: string, changes: UpdateTaskInput): Promise<Task>;
  complete(userId: string, taskId: string): Promise<CompleteTaskResult>;
  remove(userId: string, taskId: string): Promise<void>;
}

/** The task's own attributes, for re-validation when part of it changes. */
const attributesOf = (task: Task): TaskAttributes => ({
  title: task.title,
  description: task.description,
  dueAt: task.dueAt,
  priority: task.priority,
  recurrence: task.recurrence,
  reminderOffsetMinutes: task.reminderOffsetMinutes,
});

export function createTaskService(dependencies: TaskServiceDependencies): TaskService {
  const { unitOfWork, clock } = dependencies;

  return {
    async list(userId: string): Promise<Task[]> {
      return unitOfWork.run(async (repositories) => repositories.tasks.listForUser(userId));
    },

    async get(userId: string, taskId: string): Promise<Task> {
      return unitOfWork.run(async (repositories) => {
        const task = await repositories.tasks.findByIdForUser(taskId, userId);
        if (task === null) throw new TaskNotFoundError();
        return task;
      });
    },

    async create(input: CreateTaskInput): Promise<Task> {
      const attributes = normaliseTaskAttributes({
        title: input.title,
        description: input.description,
        dueAt: input.dueAt,
        priority: input.priority,
        recurrence: input.recurrence,
        reminderOffsetMinutes: input.reminderOffsetMinutes ?? DEFAULT_REMINDER_OFFSET_MINUTES,
      });
      validateTaskAttributes(attributes);

      return unitOfWork.run(async (repositories) => {
        const task = await repositories.tasks.create({
          userId: input.userId,
          title: attributes.title,
          description: attributes.description,
          dueAt: attributes.dueAt,
          priority: attributes.priority,
          recurrence: attributes.recurrence,
          parentTaskId: null,
          reminderOffsetMinutes: attributes.reminderOffsetMinutes,
        });

        await synchroniseReminder(repositories, task);
        return task;
      });
    },

    async update(userId: string, taskId: string, changes: UpdateTaskInput): Promise<Task> {
      return unitOfWork.run(async (repositories) => {
        const existing = await repositories.tasks.findByIdForUser(taskId, userId);
        if (existing === null) throw new TaskNotFoundError();

        /* Validate the task as it will be, not just the fields being changed:
           clearing a due date on a recurring task has to be rejected. */
        const merged = normaliseTaskAttributes({
          ...attributesOf(existing),
          ...(changes.title !== undefined ? { title: changes.title } : {}),
          ...(changes.description !== undefined ? { description: changes.description } : {}),
          ...(changes.dueAt !== undefined ? { dueAt: changes.dueAt } : {}),
          ...(changes.priority !== undefined ? { priority: changes.priority } : {}),
          ...(changes.recurrence !== undefined ? { recurrence: changes.recurrence } : {}),
          ...(changes.reminderOffsetMinutes !== undefined
            ? { reminderOffsetMinutes: changes.reminderOffsetMinutes }
            : {}),
        });
        validateTaskAttributes(merged);

        const patch: TaskChanges = {
          title: merged.title,
          description: merged.description,
          dueAt: merged.dueAt,
          priority: merged.priority,
          recurrence: merged.recurrence,
          reminderOffsetMinutes: merged.reminderOffsetMinutes,
        };

        const updated = await repositories.tasks.update(taskId, userId, patch);
        if (updated === null) throw new TaskNotFoundError();

        /* Picks up a moved deadline, a changed offset, or a cleared due date. */
        await synchroniseReminder(repositories, updated);
        return updated;
      });
    },

    /**
     * FR3. Completing a recurring task generates the next occurrence, linked to
     * the series by `parentTaskId` and with its own reminder.
     *
     * Completing an already-completed task is a no-op that returns the task
     * unchanged. Without that, a double-clicked button or a retried request
     * would generate a second occurrence.
     */
    async complete(userId: string, taskId: string): Promise<CompleteTaskResult> {
      return unitOfWork.run(async (repositories) => {
        const task = await repositories.tasks.findByIdForUser(taskId, userId);
        if (task === null) throw new TaskNotFoundError();
        if (task.status === 'done') return { task, nextOccurrence: null };

        const completedAt = clock.now();
        const completed = await repositories.tasks.update(taskId, userId, {
          status: 'done',
          completedAt,
        });
        if (completed === null) throw new TaskNotFoundError();

        /* A completed task has nothing left to be reminded about. */
        await repositories.reminders.deletePendingForTask(task.id);

        if (task.recurrence === null) {
          return { task: completed, nextOccurrence: null };
        }

        /*
         * Validation requires a recurring task to have a deadline, so `dueAt`
         * is present in practice. Falling back to the completion instant keeps
         * a row that predates that rule - or one written directly to the
         * database - recurring sensibly instead of crashing the request.
         */
        const advanceFrom = task.dueAt ?? completedAt;

        const occurrence = await repositories.tasks.create({
          userId,
          title: task.title,
          description: task.description,
          dueAt: nextOccurrence(advanceFrom, task.recurrence),
          priority: task.priority,
          recurrence: task.recurrence,
          /* The series is flat: every occurrence points at its root, not at the
             occurrence immediately before it, so the chain stays one hop deep. */
          parentTaskId: task.parentTaskId ?? task.id,
          reminderOffsetMinutes: task.reminderOffsetMinutes,
        });

        await synchroniseReminder(repositories, occurrence);
        return { task: completed, nextOccurrence: occurrence };
      });
    },

    async remove(userId: string, taskId: string): Promise<void> {
      return unitOfWork.run(async (repositories) => {
        /* Ownership is established before anything is deleted: calling
           deletePendingForTask first would touch another user's rows. */
        const task = await repositories.tasks.findByIdForUser(taskId, userId);
        if (task === null) throw new TaskNotFoundError();

        /* The foreign key would cascade anyway; doing it explicitly keeps the
           rule "deleting a task removes its unsent reminders" visible in the
           business logic rather than only in the schema. */
        await repositories.reminders.deletePendingForTask(taskId);

        const deleted = await repositories.tasks.delete(taskId, userId);
        if (!deleted) throw new TaskNotFoundError();
      });
    },
  };
}
