/**
 * The wire format, declared once.
 *
 * The Express handlers serialise *to* these types and the React client parses
 * *into* them, so a change to a response shape that the client has not caught up
 * with is a compile error rather than a runtime surprise. This file is the only
 * thing the two halves of `apps/web` share; neither imports the other's code.
 *
 * It describes the presentation layer's output and nothing deeper. There is no
 * domain type here and no database row - a task's wire representation carries
 * three renderings of each instant, which is a presentation concern that the
 * layers beneath know nothing about.
 */

export type TaskPriorityDto = 'low' | 'medium' | 'high';
export type TaskStatusDto = 'open' | 'done';

/** One UTC instant, rendered three ways for three different jobs. */
export interface InstantDto {
  /** ISO 8601 in UTC. The canonical value; the only one worth comparing. */
  readonly utc: string;
  /** `YYYY-MM-DDTHH:mm` in the user's zone, for `<input type="datetime-local">`. */
  readonly local: string;
  /** Human-readable, in the user's zone, e.g. `Wed 6 May 2026, 17:00`. */
  readonly display: string;
}

export interface UserDto {
  readonly id: string;
  readonly email: string;
  readonly timezone: string;
  readonly createdAt: string;
}

export interface TaskDto {
  readonly id: string;
  readonly title: string;
  readonly description: string | null;
  /** The task's DEADLINE. Not the reminder's firing time. */
  readonly dueAt: InstantDto | null;
  readonly priority: TaskPriorityDto;
  readonly status: TaskStatusDto;
  readonly recurrence: string | null;
  readonly parentTaskId: string | null;
  readonly reminderOffsetMinutes: number;
  readonly createdAt: InstantDto;
  readonly completedAt: InstantDto | null;
  readonly timezone: string;
}

export interface UserResponseBody {
  readonly user: UserDto;
}

export interface TaskResponseBody {
  readonly task: TaskDto;
}

export interface TaskListResponseBody {
  readonly tasks: readonly TaskDto[];
}

export interface CompleteTaskResponseBody {
  readonly task: TaskDto;
  /** The occurrence generated by the recurrence rule, or null. */
  readonly nextOccurrence: TaskDto | null;
}

export interface ErrorResponseBody {
  readonly error: {
    readonly message: string;
    /** Present when the failure can be attributed to one input. */
    readonly field?: string;
  };
}
